name: dart_desk_workspace
description: "Dart Desk monorepo workspace"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

# Workspace configuration
workspace:
  - packages/dart_desk
  - examples/data_models

dependencies: 
  collection: ^1.19.1
  shadcn_ui: ^0.52.1

dependency_overrides:
  dart_desk_annotation:
    path: packages/dart_desk_annotation
  dart_desk_generator:
    path: packages/dart_desk_generator
  marionette_flutter:
    path: ../../marionette_mcp/packages/marionette_flutter
  dart_desk_be_client:
    path: ../dart_desk_be/dart_desk_be_client
  signals:
    git:
      url: https://github.com/rodydavis/signals.dart.git
      path: packages/signals
  signals_core:
    git:
      url: https://github.com/rodydavis/signals.dart.git
      path: packages/signals_core
  signals_flutter:
    git:
      url: https://github.com/rodydavis/signals.dart.git
      path: packages/signals_flutter
