// This file demonstrates how to set up a Dart Desk CMS studio app.
//
// In a real project:
// 1. Annotate your data classes with dart_desk_annotation and run
//    `dart run build_runner build` to generate CmsDocumentType instances.
// 2. Implement CmsDataSource to connect to your backend.
// 3. Pass everything to CmsStudioApp.

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:dart_desk/dart_desk.dart';
import 'package:dart_desk/studio.dart';

// ---------------------------------------------------------------------------
// Document type definition
// ---------------------------------------------------------------------------

// Normally this is generated by dart_desk_generator. Shown here manually for
// illustration purposes.
final articleDocumentType = CmsDocumentType<_Article>(
  name: 'article',
  title: 'Article',
  description: 'A simple article document',
  fields: const [
    CmsStringField(
      name: 'title',
      title: 'Title',
      option: CmsStringOption(),
    ),
    CmsTextField(name: 'body', title: 'Body'),
  ],
  builder: (data) => Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        data['title']?.toString() ?? '',
        style: const TextStyle(fontWeight: FontWeight.bold),
      ),
      Text(data['body']?.toString() ?? ''),
    ],
  ),
  defaultValue: const _Article('', ''),
);

// ---------------------------------------------------------------------------
// App entry point
// ---------------------------------------------------------------------------

void main() {
  runApp(const ExampleApp());
}

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CmsStudioApp(
      dataSource: _DemoDataSource(),
      documentTypes: [articleDocumentType],
      documentTypeDecorations: [
        CmsDocumentTypeDecoration(
          documentType: articleDocumentType,
          icon: Icons.article,
        ),
      ],
      title: 'Example CMS',
      subtitle: 'Content Management',
      icon: Icons.dashboard,
    );
  }
}

// ---------------------------------------------------------------------------
// Example model using Serializable mixin
// ---------------------------------------------------------------------------

class _Article with Serializable<Map<String, dynamic>> {
  final String title;
  final String body;

  const _Article(this.title, this.body);

  @override
  Map<String, dynamic> toMap() => {'title': title, 'body': body};
}

// ---------------------------------------------------------------------------
// Minimal stub data source — replace with a real implementation
// ---------------------------------------------------------------------------

class _DemoDataSource implements CmsDataSource {
  @override
  Future<DocumentList> getDocuments(
    String documentType, {
    String? search,
    int limit = 20,
    int offset = 0,
  }) async =>
      DocumentList(documents: [], total: 0, page: 1, pageSize: 20);

  @override
  Future<CmsDocument?> getDocument(int documentId) async => null;

  @override
  Future<CmsDocument> createDocument(
    String documentType,
    String title,
    Map<String, dynamic> data, {
    String? slug,
    bool isDefault = false,
  }) =>
      throw UnimplementedError();

  @override
  Future<CmsDocument?> updateDocument(
    int documentId, {
    String? title,
    String? slug,
    bool? isDefault,
  }) =>
      throw UnimplementedError();

  @override
  Future<bool> deleteDocument(int documentId) async => false;

  @override
  Future<String> suggestSlug(String title, String documentType) async =>
      title.toLowerCase().replaceAll(' ', '-');

  @override
  Future<List<String>> getDocumentTypes() async => ['article'];

  @override
  Future<DocumentVersionList> getDocumentVersions(
    int documentId, {
    int limit = 20,
    int offset = 0,
  }) async =>
      DocumentVersionList.empty();

  @override
  Future<DocumentVersion?> getDocumentVersion(int versionId) async => null;

  @override
  Future<Map<String, dynamic>?> getDocumentVersionData(int versionId) async =>
      null;

  @override
  Future<DocumentVersion> createDocumentVersion(
    int documentId, {
    String status = 'draft',
    String? changeLog,
  }) =>
      throw UnimplementedError();

  @override
  Future<CmsDocument> updateDocumentData(
    int documentId,
    Map<String, dynamic> updates, {
    String? sessionId,
  }) =>
      throw UnimplementedError();

  @override
  Future<DocumentVersion?> publishDocumentVersion(int versionId) =>
      throw UnimplementedError();

  @override
  Future<DocumentVersion?> archiveDocumentVersion(int versionId) =>
      throw UnimplementedError();

  @override
  Future<bool> deleteDocumentVersion(int versionId) async => false;

  @override
  Future<MediaUploadResult> uploadImage(
          String fileName, Uint8List fileData) =>
      throw UnimplementedError();

  @override
  Future<MediaUploadResult> uploadFile(String fileName, Uint8List fileData) =>
      throw UnimplementedError();

  @override
  Future<bool> deleteMedia(int fileId) async => false;

  @override
  Future<MediaFile?> getMedia(int fileId) async => null;

  @override
  Future<List<MediaFile>> listMedia({int limit = 50, int offset = 0}) async =>
      [];
}
