name: data_models
description: Example data models for the dart_desk CMS showcase.
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dart_desk_annotation:
    git:
      url: https://github.com/ThangVuNguyenViet/dart_desk.git
      path: packages/dart_desk_annotation
  dart_desk:
    path: ../../packages/dart_desk
  dart_mappable: ^4.6.1
  shadcn_ui: ^0.52.1

dev_dependencies:
  build_runner: ^2.13.1
  dart_mappable_builder: ^4.6.1
  dart_desk_generator:
    git:
      url: https://github.com/ThangVuNguyenViet/dart_desk.git
      path: packages/dart_desk_generator
  lints: ^6.0.0
