name: example_app
description: Standalone preview app for dart_desk example widgets.
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.1
  intl: ^0.20.2
  serverpod_flutter: ^3.3.1
  data_models:
    git:
      url: https://github.com/ThangVuNguyenViet/dart_desk.git
      path: examples/data_models
  dart_desk:
    path: ../../packages/dart_desk
  dart_desk_client:
    git:
      url: https://github.com/ThangVuNguyenViet/dart_desk_be.git
      path: dart_desk_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  serverpod_auth_idp_flutter: ^3.3.1

flutter:
  uses-material-design: true
