name: dart_desk_annotation
description: Annotations and field definitions for the Dart Desk CMS framework.
version: 0.1.0
homepage: https://github.com/vietthangvunguyen/dart_desk
repository: https://github.com/vietthangvunguyen/dart_desk
topics:
  - cms
  - annotations
  - flutter

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.9.1
  flutter:
    sdk: flutter
  form_builder_validators: ^11.2.0
