name: dart_desk_annotation
description: Annotations and field definitions for the Dart Desk CMS framework.
version: 0.1.1
homepage: https://github.com/ThangVuNguyenViet/dart_desk
repository: https://github.com/ThangVuNguyenViet/dart_desk
issue_tracker: https://github.com/ThangVuNguyenViet/dart_desk/issues
topics:
  - desk
  - annotations
  - flutter

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.9.1
  flutter:
    sdk: flutter
  form_builder_validators: ^11.2.0
  dart_mappable: ^4.0.0
