builders:
  deskBuilder:
    target: ":dart_desk_generator"
    import: "package:dart_desk_generator/dart_desk_generator.dart"
    builder_factories: ["deskBuilder"]
    build_extensions: {".dart": [".desk.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
