name: dart_desk
description: "CMS studio interface with inputs, validators, and runtime components for Dart Desk applications"
publish_to: 'none'
version: 0.1.0

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  dart_desk_annotation:
    path: ../dart_desk_annotation
  dart_desk_be_client:
    path: ../../../dart_desk_be/dart_desk_be_client
  flutter:
    sdk: flutter
  shadcn_ui: ^0.52.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.0
  signals: ^6.1.0
  flutter_resizable_container: ^4.2.0
  super_editor: ^0.3.0-dev.50
  disco: ^1.0.3+1
  zenrouter: ^2.0.3
  marionette_flutter:
    path: ../../../../marionette_mcp/packages/marionette_flutter
  font_awesome_flutter: ^10.8.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
