name: dart_desk
description: "CMS studio interface with inputs, validators, and runtime components for Dart Desk applications"
version: 0.1.0
homepage: https://github.com/vietthangvunguyen/dart_desk
repository: https://github.com/vietthangvunguyen/dart_desk
topics:
  - cms
  - flutter
  - content-management

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  dart_desk_client: ^0.1.0
  dart_desk_annotation:
    git:
      url: https://github.com/ThangVuNguyenViet/dart_desk.git
      path: packages/dart_desk_annotation
  flutter:
    sdk: flutter
  shadcn_ui: ^0.52.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.0
  serverpod_flutter: ^3.3.1
  serverpod_auth_core_flutter: ^3.3.1
  serverpod_auth_idp_flutter: ^3.3.1
  signals: ^6.3.0
  flutter_resizable_container: ^4.2.0
  super_editor: ^0.3.0-dev.50
  get_it: ^9.2.1
  zenrouter: ^2.0.3
  marionette_flutter: ^0.4.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.0
  collection: ^1.19.1
  blurhash_dart: ^1.2.1
  crypto: ^3.0.6
  image: ^4.5.0
  image_picker_platform_interface: ^2.10.0
  plugin_platform_interface: ^2.1.8
  super_drag_and_drop: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
