import 'package:flutter/widgets.dart';

import 'fields/base/field.dart';
import 'serializable.dart';

/// Represents a document type (schema) in the CMS.
class DocumentType<T> {
  /// Unique identifier for this document type
  final String name;

  /// Display title for this document type
  final String title;

  /// Description of this document type
  final String description;

  /// List of fields for this document type
  final List<CmsField> fields;

  /// Required builder function to create a widget from the config data
  final Widget Function(Map<String, dynamic> data) builder;

  /// Function to create a default instance of T
  final T? defaultValue;
  const DocumentType({
    required this.name,
    required this.title,
    required this.description,
    required this.fields,
    required this.builder,
    this.defaultValue,
  });
}

/// A partial document type definition without a preview builder.
///
/// Generated by dart_desk_generator for each @CmsConfig class.
/// Call [build] in your cms_app to produce a full [DocumentType]
/// by supplying the preview builder there.
///
/// Example:
/// ```dart
/// final myDocumentType = myTypeSpec.build(
///   builder: (data) => MyScreen(config: MyConfigMapper.fromMap(data)),
/// );
/// ```
class DocumentTypeSpec<T> {
  /// Unique identifier for this document type
  final String name;

  /// Display title for this document type
  final String title;

  /// Description of this document type
  final String description;

  /// List of fields for this document type
  final List<CmsField> fields;

  /// Optional default instance of T
  final T? defaultValue;

  const DocumentTypeSpec({
    required this.name,
    required this.title,
    required this.description,
    required this.fields,
    this.defaultValue,
  });

  /// Produces a full [DocumentType] by supplying a preview [builder].
  ///
  /// The [builder] receives the raw CMS data map and must return a Widget.
  /// This is required — it is a compile error to call [build] without it.
  DocumentType<T> build({
    required Widget Function(Map<String, dynamic> data) builder,
  }) {
    return DocumentType<T>(
      name: name,
      title: title,
      description: description,
      fields: fields,
      builder: builder,
      defaultValue: defaultValue,
    );
  }
}
